stages:
  - test

test:
  image: node:latest
  stage: test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run testHeadless
    # run Cypress tests
    - npm run e2e